# Generated by Django 5.1.3 on 2024-11-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('education', 'Education'), ('experience', 'Experience'), ('contact', 'Contact')], max_length=20)),
                ('image', models.ImageField(upload_to='page_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
