# Generated by Django 5.1.3 on 2024-11-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_imageupload_delete_pageimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('home', 'Home'), ('about', 'About'), ('education', 'Education'), ('experience', 'Experience'), ('contact', 'Contact')], max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='section_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
